### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ralphllama** [finestructure/homebrew-tap#1]
I tried to install Arena today and got the following result:

$ brew install finestructure/tap/arena
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 16 formulae.

==> Installing arena from finestructure/tap
==> Downloading https://github.com/finestructure/Arena/archive/1.2.0.tar.gz
Already downloaded: /Users/ward/Library/Caches/Homebrew/downloads/4631473b1f32ec876de3dd3cc382f6b1060fc2b931bbcd0e1056a9209a6234b9--Arena-1.2.0.tar.gz
==> swift build --configuration release --disable-sandbox
Last 15 lines from /Users/ward/Library/Logs/Homebrew/arena/01.swift:
2020-11-24 11:58:34 -0700

swift
build
--configuration
release
--disable-sandbox

error: terminated(72): HOMEBREW_OPTFLAGS=-march=nehalem HOMEBREW_FORMULA_PREFIX=/usr/local/Cellar/arena/1.2.0 HOMEBREW_NO_ANALYTICS=1 HOMEBREW_GIT_CONFIG_FILE=/usr/local/Homebrew/.git/config HOMEBREW_CC_LOG_PATH=/Users/ward/Library/Logs/Homebrew/arena/01.swift HOMEBREW_DEFAULT_LOGS=/Users/ward/Library/Logs/Homebrew HOMEBREW_REQUIRED_RUBY_VERSION=2.6.3 HOMEBREW_BOTTLE_DEFAULT_DOMAIN=https://homebrew.bintray.com HOMEBREW_DEFAULT_CACHE=/Users/ward/Library/Caches/Homebrew SHLVL=0 HOMEBREW_ISYSTEM_PATHS=/usr/local/include:/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.rodsMMICmN/Listeners HOMEBREW_MACOS_VERSION_NUMERIC=101507 HOMEBREW_ARCHFLAGS= LC_ALL=en_US.UTF-8 CC=clang OBJCXX=clang++ __CF_USER_TEXT_ENCODING=0x1F6:0x0:0x0 HOMEBREW_BREW_DEFAULT_GIT_REMOTE=https://github.com/Homebrew/brew HOMEBREW_RUBY_PATH=/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby HOMEBREW_GIT=git HOMEBREW_PREFIX=/usr/local GOPATH=/Users/ward/Library/Caches/Homebrew/go_mod_cache HOMEBREW_CXX=clang++ HOMEBREW_PRODUCT=Homebrew HOMEBREW_OPT=/usr/local/opt CPATH=/usr/local/include SHELL=/bin/bash PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15 TERM=xterm-256color CMAKE_PREFIX_PATH=/usr/local TMP=/private/tmp HOMEBREW_BREW_GIT_REMOTE=https://github.com/Homebrew/brew HOMEBREW_PREFER_CLT_PROXIES=1 HOMEBREW_DEFAULT_TEMP=/private/tmp HOMEBREW_ENV=super CXX=clang++ HOMEBREW_COMMAND_DEPTH=2 HOMEBREW_EDITOR=vim HOMEBREW_CC=clang HOMEBREW_CACHE=/Users/ward/Library/Caches/Homebrew LOGNAME=ward PATH=/usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/bin:/bin:/usr/sbin:/sbin HOME=/private/tmp/arena-20201124-85276-1rgj5oi/Arena-1.2.0/.brew_home TEMP=/private/tmp HOMEBREW_OPTIMIZATION_LEVEL=Os HOMEBREW_DEVELOPER_DIR=/Library/Developer/CommandLineTools HOMEBREW_LIBRARY=/usr/local/Homebrew/Library MAKEFLAGS=-j12 ACLOCAL_PATH=/usr/local/share/aclocal HOMEBREW_ERROR_PIPE=/private/tmp/homebrew20201124-84308-dgzi2e/socket HOMEBREW_MACOS_VERSION=10.15.7 HOMEBREW_LOGS=/Users/ward/Library/Logs/Homebrew HOMEBREW_VERSION=2.5.11 HOMEBREW_USER_AGENT_CURL=Homebrew/2.5.11 (Macintosh; Intel Mac OS X 10.15.7) curl/7.64.1 HOMEBREW_CORE_GIT_REMOTE=https://github.com/Homebrew/homebrew-core HOMEBREW_LIBRARY_PATHS=/usr/local/lib:/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries HOMEBREW_BOTTLE_DOMAIN=https://homebrew.bintray.com HOMEBREW_CURL=curl HOMEBREW_DEPENDENCIES= CARGO_HOME=/Users/ward/Library/Caches/Homebrew/cargo_cache USER=ward HOMEBREW_AUTO_UPDATE_CHECKED=1 HOMEBREW_RUBY_WARNINGS=-W0 HOMEBREW_PROCESSOR=Intel CURL_HOME=/Users/ward _JAVA_OPTIONS=-Duser.home=/Users/ward/Library/Caches/Homebrew/java_cache HOMEBREW_REPOSITORY=/usr/local/Homebrew HOMEBREW_BREW_FILE=/usr/local/bin/brew HOMEBREW_CCCFG=sa SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk HOMEBREW_SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk HOMEBREW_OS_VERSION=macOS 10.15.7 TMPDIR=/private/tmp LIBRARY_PATH=/usr/local/lib OBJC=clang HOMEBREW_SYSTEM=Macintosh HOMEBREW_CELLAR=/usr/local/Cellar HOMEBREW_TEMP=/private/tmp HOMEBREW_CORE_DEFAULT_GIT_REMOTE=https://github.com/Homebrew/homebrew-core GOCACHE=/Users/ward/Library/Caches/Homebrew/go_cache PWD=/Users/ward HOMEBREW_USER_AGENT=Homebrew/2.5.11 (Macintosh; Intel Mac OS X 10.15.7) CMAKE_INCLUDE_PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers HOMEBREW_MINIMUM_GIT_VERSION=2.14.3 CMAKE_LIBRARY_PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries /usr/bin/xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH
    

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/finestructure/homebrew-tap/issues

I had just installed Homebrew and it, in turn, had updated my Xcode tools.

Any suggestions for getting Arena installed?

**Comment by finestructure** [comment]
Mmmm, very strange. You say you've updated your Xcode tools - could you confirm your Xcode version and run the install command again, please?

```
xcode-select -p
xcode-select --install
```

**Comment by ralphllama** [comment]
Thanks for the response. Here’s what I found:

Xcode version is 12.2 (12B45b)

The results of the commands was:

$ xcode-select -p
/Applications/Xcode.app/Contents/Developer

$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

Digging into the contents of Xcode, I found xctest in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Xcode/Agents/xctest

with an alas to that in
/Applications/Xcode.app/Contents/Developer/usr/bin/

Regards,
Edward Stanke

**Comment by finestructure** [comment]
I'm at a loss. You don't have any other versions of Xcode installed, do you? I'm on Version 12.2 (12B45b) as well and have just reinstalled:

```
❯ xcode-select -p
/Applications/Xcode_12.2.app/Contents/Developer
❯ brew reinstall finestructure/tap/arena
Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.

==> Downloading https://github.com/finestructure/Arena/archive/1.2.0.tar.gz
==> Downloading from https://codeload.github.com/finestructure/Arena/tar.gz/1.2.0
                                    -=O=-                         #   #  # #
==> Reinstalling finestructure/tap/arena
==> swift build --configuration release --disable-sandbox
🍺  /usr/local/Cellar/arena/1.2.0: 5 files, 2.1MB, built in 46 seconds
```

I know this doesn't help you but it least we know it works in principle :) I've also tested again with Catalina and Xcode 11 just now, that installs cleanly as well.

How did you install Xcode? Via the App Store? Can you perhaps try to reinstall via the xip archive?

**Comment by ralphllama** [comment]
Thank you for your help. I reinstalled the command line tools from the disk image file and the Arena install went just fine.

I really appreciate your time.

Thank you,

Edward Stanke

**Comment by finestructure** [comment]
You're welcome, great to hear it's working now! I'll be closing the issue then.
